#!/bin/sh

set -e

if [ -n "${IF_PEER_NETNS}" -a -n "${IF_PEER_IFACE}" ]
then
    # Remove the veth pair
    ip link del ${IFACE}

    # Remove netns
    ip netns delete "${IF_PEER_NETNS}"

    rm -rf /run/network.${IF_PEER_NETNS}/*
fi

